{% set version = "0.4.0" %}

package:
  name: missingno
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/missingno/missingno-{{ version }}.tar.gz
  sha256: f262546691f22a79933faa23fe97acce68e9c919a1a8d1e8b71fd7f16ad4941b

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn

test:
  imports:
    - missingno

about:
  home: https://github.com/ResidentMario/missingno
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Missing data visualization module for Python.'

extra:
  recipe-maintainers:
    - ericmjl
