travis:
  secure:
    BINSTAR_TOKEN: PnAA5pkXnn/rnQlXaLHQjfTBbHjUsHRTTcvo/+9CWLtlpFPnXJwnzax+Tz0hsZO5L0zznhhkMLuNrS2KnbVpHIOKpOFhk3u3Z0gweYk3zNTIoF8E3OKWTxViDUElOkBbuHdEVaeC2g8dMuXUe05qRF17eRpkYsR3UpojgCjveedyhEp5CG10PJ6CiLSkVZoJzzg0aDHcqmoIq+UCyfFDN2PJNQPYZuQfAdpyjEH1Zp5mgmIyxmRXc+G9B95Zdie12WdvlLUUsA/rC/axsNw37jCa3NncfM/3uPYDTbi1U48lCyJRqmWbJTsYRvwf3/voQdGFjk8AEoSdLIHP0Mk0hXw3ElPcPLCIB54sB/MvG/A2GAsQVeUL7f5LwQrR2iWRe39NEmrnGi/AR6iacEaQoMqvyyXeZuSnx/FZvZJ0dgluJaThh1nRyhUPZHZBBmERX/nwPB0oqjflgxYmqBOQbRK7SnPHPjUA2lJAJ9UovXNk8thL38+ZlR/dH2pGRdym0CdfnBzOWAO3O9ykISvTmsECnKnyRBTPQ/zpoJ98DJrMCpsLtYCux6Up/Q1IZsFSr+K8lPy15IyI2vcxAS3L1jeLoec6TdmhWA+jG5eCiFpVQ+Ce8bKucUa0Uwf+bn1DPWAdQKEUhc4OV+wLY0SBQdLrB369BPlR/Gmu+xAdhHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
