travis:
  secure:
    BINSTAR_TOKEN: iElqZ2Cd4VHcuTrfLLXPz6UJ+IGoCSBp9p9LyiwgC4IjJdiKaEKJZVD5bXS/a1u6iyM4FcwUx9uVtzIsx0bl6YZNbhxResTgzYmXycdWfsx3rUIv02y1666gizHooApcRALgtqz/pqYcpTp+RcvFxwmbrvIj1OWXLmBalHLcWCHY409n8BgFlOT/VjqsGksm5LwjF3evpL9kxfRPfFSiuyXZwoKW5AJjOv9JZbmoQNYQrviaGGmWcfbJrQt0N7wbwxRf3Rr56RPoG4sfErFlt+LXSTcm5Ulc2XHQiYIzMrJsfA40j+WWGVSddIharifol/fsAvpfwSPKtG+3SbPbRSNGEyg8pW55t8mhElJU2dFuIFIAK69ddqDUGQKrCk3ptn1Y6e71kK9ZLgTYPx5nAi1+jyLyHEMD9GK09UYI8xkFfjQt22RLjbFXCtQ8gnSARu8epXdXGVeP2RV281OvKis6OT3vOuOjgmKWXs2llCVpenyEQNbFnkzRLC+lT/mbOWMoYptQtf+qwOtNVNzbNuHUPRPTYnHWs/ZzkxXfYtRgOGlQDjn1GGYjqmb6cjU1keE+ao0yYNBLjvhrFWrm/0x0J9uqU06Wrbi5/1HsJB+D7UEpQZxCn/XRVpdLUzN2MZ+P7rg2WG7OuAAo1OFV4USfeh6LfXKN7MK11WPgem0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
