travis:
  secure:
    BINSTAR_TOKEN: Yp7m1SnxEk8trltG0skJIKfNnRpA6sCUG1pLkPolu9c169sQ9FmlsYFx82yf17cQvL+WvS/dx4ieU0Z8jn36HnjX2ZwqIgC7LLNzD6cgP8EJQMu6VHuhRy1lkSoQTP4hKnd1EOgTo2IZTCjpooUbDkxBSjMW7OjLTyD5yslBWKnXb4JRO+qziQTNb8BPwhoTxKrEODZkx2vISd3BHt62gTWtuJX0Q03QiTXygpT20ufyh2pdPHRPFs8z04fiOh9HGoM+J6JdK/s8nrCGeQieuOYYyHJKkkZbjJfWP/LvKgM/nNOqeanl6p9tPLugYzkPE7EqFqVHC1oUajqsNEBxnp7NbgcUDTVsaVRpP4v6D+A6pY18rAOhEAQgkKOjCokybNnxTCykCpIdZlj+QSvxqi9DpT86DWR2GI1KuqPO/NlUjl5toAtW1WbE4hI+w4ESoj3vcp/3xBAQo7MVh/2Y9onAMuqUir4WGxyP7picCKzTtR08VoF367p9Jdgn2fRGxaZbmL9YnEy9VFmM3o8WYnLDRx0xgkYcQS5EunPJ1PuWrYumFgBTiolww5WTFxWBW/MWHV3vJXT9dzld85qFBOP3jU2ZiH9DYcO5CgtVJWcrSWNMiDQ4um0sJjSIlA7eb3JjTBz/PbovA6PjSxY/AQvWKEwj9OgvnmyDJHH4Ads=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
